# fly.toml app configuration file generated for tarotkarten-prompt-generator on 2025-08-31T18:36:46+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'tarotkarten-prompt-generator'
